name: food_recognizer_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  image: ^4.5.4
  provider: ^6.1.5+1
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mobilenet.tflite
    - assets/probability-labels-en.txt
